### ISSUE TITLE
[Feature request] Standalone version

### ISSUE THREAD

**Issue by imagoiq** [prettier/prettier-synchronized#15]
Hi,
Maybe, it's already possible, but it would be great to be able to use it as a standalone version. Also can you clarify what's the intent with this version. Is it a temporary solution or will it be supported for long-term?

Thanks per advance

**Comment by fisker** [comment]
Unfortunately, it's not possible to make Prettier sync in browser.

> since Atomics.wait is blocking, it’s not possible to call it on the main thread.

https://v8.dev/features/atomics

**Comment by imagoiq** [comment]
Thanks for the info.

**Comment by kerryj89** [comment]
I think it would be nice if the description for prettier-synchronized made this more clear.  I used Prettier to format code output in Storybook, saw that Prettier 3 is async, and saw `Synchronous version of Prettier` and thought I could swap it out.  Then I read this thread 😅

**Comment by marcelino-borges** [comment]
> I think it would be nice if the description for prettier-synchronized made this more clear. I used Prettier to format code output in Storybook, saw that Prettier 3 is async, and saw `Synchronous version of Prettier` and thought I could swap it out. Then I read this thread 😅

Same here
