### ISSUE TITLE
Use `synckit` to simply and support other features like yarn PnP and experimental loader

### ISSUE THREAD

**Issue by JounQin** [prettier/prettier-synchronized#2]
I'd like to raise a PR if you agree.

See also

- https://github.com/un-ts/synckit
- https://github.com/un-ts/synckit/pull/98
- https://github.com/un-ts/synckit/pull/103

Besides, I'm trying to make `synckit` work on browsers with Web Workers at https://github.com/un-ts/synckit/issues/31.

**Comment by fisker** [comment]
No, thanks. But we may want try it if PnP support is requested.

**Comment by JounQin** [comment]
That's OK.

**Comment by rattrayalex** [comment]
FWIW, this repo did not work for me – it just hung, without printing anything, even in a REPL – and using `synckit` with the `next` branch of prettier did work for me. Performance was not too bad either.
